// Generates sw.js - a service worker that precaches every course asset so the
// deployed site (GitHub Pages) keeps working with no internet after the first
// visit. Re-run this after adding pages, images, fonts, or characters:
//   node generate_sw.js
const fs = require('fs');
const path = require('path');

const PAGES = [
    'index.html', 'writing.html', 'ocean.html', 'spaceship.html', 'review.html',
    'questions.html', 'voicepractice.html', 'sentencebuilder.html', 'ebook.html',
    'workbook.html', 'arcade.html', 'kanjiride.html'
];

const assets = ['./'];
for (const p of PAGES) assets.push(p);
assets.push('kanjivg_data.js');
assets.push('curriculum.js');
assets.push('wordcats.js');
assets.push('activities.js');
for (let y = 1; y <= 5; y++) assets.push('curriculum_y' + y + '.js');
assets.push('Underwater Theme.mp3');
for (const f of fs.readdirSync('fonts')) assets.push('fonts/' + f);
for (const f of fs.readdirSync('ocean_images')) assets.push('ocean_images/' + f);

// Verify everything exists before baking the list
for (const a of assets) {
    if (a === './') continue;
    if (!fs.existsSync(a)) { console.error('MISSING: ' + a); process.exit(1); }
}

// Bump the version whenever content changes so clients pick up updates
const version = 'v' + new Date().toISOString().slice(0, 10).replace(/-/g, '') + '-' + Date.now().toString(36);

const sw = `// Service worker for offline use - generated by generate_sw.js, do not edit by hand
const CACHE = 'fiona-japanese-${version}';
// The ebook's 100MB of workbook page images live in a STABLE cache that
// survives deploys - they are runtime-cached by ebook.html's pre-warm, and
// wiping them on every version bump would silently break the book offline.
const PAGES_CACHE = 'fiona-workbook-pages-v1';
const ASSETS = ${JSON.stringify(assets.map(a => encodeURI(a)), null, 0)};

function isBookPage(url) {
    return new URL(url).pathname.indexOf('WorkbookPages_Correct/') !== -1;
}

self.addEventListener('install', e => {
    e.waitUntil(
        caches.open(CACHE)
            .then(c => c.addAll(ASSETS))
            .then(() => self.skipWaiting())
    );
});

self.addEventListener('activate', e => {
    e.waitUntil(
        caches.keys()
            .then(keys => Promise.all(keys.filter(k => k !== CACHE && k !== PAGES_CACHE).map(k => caches.delete(k))))
            .then(() => self.clients.claim())
    );
});

// iOS Safari requires 206 responses for media byte-range requests -
// serve them by slicing the cached full body
function rangedResponse(req, res) {
    const range = /bytes=(\\d+)-(\\d*)/.exec(req.headers.get('range') || '');
    if (!range) return Promise.resolve(res);
    return res.arrayBuffer().then(buf => {
        const start = +range[1];
        const end = range[2] ? +range[2] : buf.byteLength - 1;
        return new Response(buf.slice(start, end + 1), {
            status: 206,
            statusText: 'Partial Content',
            headers: {
                'Content-Type': res.headers.get('Content-Type') || '',
                'Content-Range': 'bytes ' + start + '-' + end + '/' + buf.byteLength,
                'Content-Length': String(end - start + 1)
            }
        });
    });
}

self.addEventListener('fetch', e => {
    if (e.request.method !== 'GET') return;
    const accept = e.request.headers.get('accept') || '';
    if (e.request.mode === 'navigate' || accept.includes('text/html')) {
        // Pages: network first so updates apply on the next load,
        // cache fallback keeps them working offline
        e.respondWith(
            fetch(e.request).then(resp => {
                if (resp.ok) {
                    const copy = resp.clone();
                    caches.open(CACHE).then(c => c.put(e.request, copy));
                }
                return resp;
            }).catch(() => caches.match(e.request, { ignoreSearch: true }))
        );
        return;
    }
    // Everything else (fonts, images, audio, data): cache first for speed
    const bucket = isBookPage(e.request.url) ? PAGES_CACHE : CACHE;
    e.respondWith(
        caches.match(e.request, { ignoreSearch: true }).then(hit => {
            if (hit) {
                return e.request.headers.get('range') ? rangedResponse(e.request, hit.clone()) : hit;
            }
            return fetch(e.request).then(resp => {
                if (resp.ok && resp.status === 200 && new URL(e.request.url).origin === self.location.origin) {
                    const copy = resp.clone();
                    caches.open(bucket).then(c => c.put(e.request, copy));
                }
                return resp;
            });
        })
    );
});
`;

fs.writeFileSync('sw.js', sw);
console.log('sw.js written: ' + assets.length + ' precached assets, cache ' + version);
