// Builds kanjivg_data.js: embeds KanjiVG stroke path data for every character
// taught in writing.html and ocean.html, so stroke guides and writing-accuracy
// scoring work fully offline (including when opened via file://).
// Re-run after adding new characters to either page:
//   node generate_kanjivg_data.js
const fs = require('fs');
const https = require('https');

const chars = new Set();
for (const f of ['writing.html', 'ocean.html']) {
    const html = fs.readFileSync(f, 'utf8');
    for (const m of html.matchAll(/char:\s*'(.)'/g)) chars.add(m[1]);
}
const list = [...chars];
console.log('characters found:', list.length);

function fetchUrl(url) {
    return new Promise((resolve, reject) => {
        https.get(url, res => {
            if (res.statusCode !== 200) { res.resume(); return reject(new Error('HTTP ' + res.statusCode + ' ' + url)); }
            let data = '';
            res.on('data', d => data += d);
            res.on('end', () => resolve(data));
        }).on('error', reject);
    });
}

async function main() {
    const out = {};
    const failed = [];
    for (let i = 0; i < list.length; i += 8) {
        const batch = list.slice(i, i + 8);
        await Promise.all(batch.map(async c => {
            const code = c.codePointAt(0).toString(16).padStart(5, '0');
            const url = 'https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/' + code + '.svg';
            try {
                const svg = await fetchUrl(url);
                const ds = [];
                const re = /<path[^>]*\sd="([^"]+)"/g;
                let m;
                while ((m = re.exec(svg)) !== null) ds.push(m[1]);
                if (ds.length === 0) throw new Error('no paths');
                out[c] = ds;
            } catch (e) {
                failed.push(c + ' (' + e.message + ')');
            }
        }));
        process.stdout.write('\r' + Math.min(i + 8, list.length) + '/' + list.length);
    }
    console.log('');
    const js = '// KanjiVG stroke data (one SVG path per stroke, in stroke order)\n' +
        '// Source: KanjiVG (c) Ulrich Apel, CC BY-SA 3.0 - https://kanjivg.tagaini.net\n' +
        '// Generated by generate_kanjivg_data.js - do not edit by hand.\n' +
        'window.KVG_DATA = ' + JSON.stringify(out) + ';\n';
    fs.writeFileSync('kanjivg_data.js', js);
    console.log('embedded:', Object.keys(out).length, 'chars,', Math.round(js.length / 1024) + 'KB');
    if (failed.length) {
        console.log('FAILED:', failed.join(', '));
        process.exit(1);
    }
}
main();
