// Generates sw.js - a service worker that precaches every course asset so the
// deployed site (GitHub Pages) keeps working with no internet after the first
// visit. Re-run this after adding pages, images, fonts, or characters:
//   node generate_sw.js
const fs = require('fs');
const path = require('path');

const PAGES = [
    'index.html', 'writing.html', 'ocean.html', 'spaceship.html', 'review.html',
    'questions.html', 'voicepractice.html', 'sentencebuilder.html', 'ebook.html'
];

const assets = ['./'];
for (const p of PAGES) assets.push(p);
assets.push('kanjivg_data.js');
assets.push('Underwater Theme.mp3');
for (const f of fs.readdirSync('fonts')) assets.push('fonts/' + f);
for (const f of fs.readdirSync('ocean_images')) assets.push('ocean_images/' + f);

// Verify everything exists before baking the list
for (const a of assets) {
    if (a === './') continue;
    if (!fs.existsSync(a)) { console.error('MISSING: ' + a); process.exit(1); }
}

// Bump the version whenever content changes so clients pick up updates
const version = 'v' + new Date().toISOString().slice(0, 10).replace(/-/g, '') + '-' + Date.now().toString(36);

const sw = `// Service worker for offline use - generated by generate_sw.js, do not edit by hand
const CACHE = 'fiona-japanese-${version}';
const ASSETS = ${JSON.stringify(assets.map(a => encodeURI(a)), null, 0)};

self.addEventListener('install', e => {
    e.waitUntil(
        caches.open(CACHE)
            .then(c => c.addAll(ASSETS))
            .then(() => self.skipWaiting())
    );
});

self.addEventListener('activate', e => {
    e.waitUntil(
        caches.keys()
            .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
            .then(() => self.clients.claim())
    );
});

self.addEventListener('fetch', e => {
    if (e.request.method !== 'GET') return;
    const accept = e.request.headers.get('accept') || '';
    if (e.request.mode === 'navigate' || accept.includes('text/html')) {
        // Pages: network first so updates apply on the next load,
        // cache fallback keeps them working offline
        e.respondWith(
            fetch(e.request).then(resp => {
                if (resp.ok) {
                    const copy = resp.clone();
                    caches.open(CACHE).then(c => c.put(e.request, copy));
                }
                return resp;
            }).catch(() => caches.match(e.request, { ignoreSearch: true }))
        );
        return;
    }
    // Everything else (fonts, images, audio, data): cache first for speed
    e.respondWith(
        caches.match(e.request, { ignoreSearch: true }).then(hit => {
            if (hit) return hit;
            return fetch(e.request).then(resp => {
                if (resp.ok && new URL(e.request.url).origin === self.location.origin) {
                    const copy = resp.clone();
                    caches.open(CACHE).then(c => c.put(e.request, copy));
                }
                return resp;
            });
        })
    );
});
`;

fs.writeFileSync('sw.js', sw);
console.log('sw.js written: ' + assets.length + ' precached assets, cache ' + version);
